#!/usr/bin/env python3
"""Render the eight Build capability pages.

Content lives in tools/build_pages.json. The track record on each page is
pulled straight out of tools/projects.json using the same sector classifier
that drives projects.html, so the counts and the named clients on a capability
page always agree with the project database rather than being typed in by hand
and slowly going stale.

Where a page has little or no delivered work behind it - renewable energy in
particular - the content carries an 'evidence_note' saying so. Do not replace
that with an implied track record.

Usage:
    python3 tools/build_pages.py build     regenerate the eight pages
    python3 tools/build_pages.py check     fail if any page is out of date
"""
from __future__ import annotations

import html
import importlib.util
import json
import os
import re
import sys
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = "https://www.uniconsa.co.za"
DATA = os.path.join(ROOT, "tools", "build_pages.json")

START = "<!-- BUILD:BODY:START - generated by tools/build_pages.py, do not edit by hand -->"
END = "<!-- BUILD:BODY:END -->"
NAV_END = "<!-- CHROME:NAV:END -->"
FOOT_START = "<!-- CHROME:FOOTER:START"

HERO_IMG = {
    "water-engineering": ("bestphotos/main/Circular_Concrete_Reservoir_Construction_20161123.jpg",
                          "Circular concrete reservoir under construction"),
    "civil-engineering": ("bestphotos/main/Concrete%20Bridge%20Construction%20-%20Unicon%20SA.jpg",
                          "Concrete bridge under construction"),
    "structural-engineering": ("bestphotos/main/Dome-Roof-Tank-Scaffolding-Unicon-Construction.jpg",
                               "Scaffolding around a dome roof tank"),
    "general-building": ("bestphotos/main/construction-site-crane-building-scaffolding-Pietermaritzburg-Invesco%20Centre.JPG",
                         "Tower crane and scaffolding over a retail centre build"),
    "industrial-logistics": ("bestphotos/main/unicon-construction-industrial-vessel-lift-installation.jpg",
                             "Crane lifting a large industrial vessel into position"),
    "agricultural-engineering": ("bestphotos/main/Agrico_Pivot_Irrigation_System_20210830.jpg",
                                 "Pivot irrigation system on farmland"),
    "mining-infrastructure": ("bestphotos/main/Unicon_Water_Reservoir_Dome_Roof_Concrete_Construction_Roof_Structure_20170218_Mountain_Landscape.jpg",
                              "Reinforced concrete dome roof on a circular water reservoir"),
    "renewable-energy": ("Unicon-earthworks/main/unicon-construction-aerial-excavation-earthmoving-site-IMG_5067.JPG",
                         "Aerial view of bulk excavation and earthmoving"),
}
MID_IMG = {
    "water-engineering": ("bestphotos/main/Unicon-Construction-Water-Reservoir-Lining-Roof-20170325-Site-AerialView.jpg",
                          "Aerial view of reservoir lining and roof works"),
    "civil-engineering": ("bestphotos/main/Unicon-Construction-Resources-Precast-Concrete-Bridge-Beam-Lift-20141210.jpg",
                          "Crane lifting a precast concrete bridge beam"),
    "structural-engineering": ("bestphotos/main/Unicon_Concrete_Dome_Pour_Reinforcement_Construction_Mountain_Landscape_20170325.jpg",
                               "Reservoir dome reinforcement ahead of a concrete pour"),
    "general-building": ("bestphotos/main/Unicon-Construction-Resources-Steel-Frame-Building-Site-Groundwork-2026-05-08.JPG",
                         "Structural steel frame rising over groundworks"),
    "industrial-logistics": ("bestphotos/main/Unicon-Manitou-Telehandler-Steel-Structure-Construction-Resource-Product-Building-Element-20190228.jpg",
                             "Telehandler positioning steel structure"),
    "agricultural-engineering": ("Unicon-earthworks/main/unicon-construction-agricultural-terracing-earthworks-site-dji-20241120.JPG",
                                 "Agricultural terracing earthworks from the air"),
    "mining-infrastructure": ("bestphotos/main/Unicon_Construction_Circular_Concrete_Wall_Scaffolding_20170220.jpg",
                              "Scaffolding around a circular concrete reservoir wall"),
    "renewable-energy": ("bestphotos/main/Unicon_JCB_Excavator_Earthworks_Canal_RedSoil_Landscape_DSC_0034.JPG",
                         "Excavator shaping a canal through red soil"),
}
RAW = "https://raw.githubusercontent.com/chrisnott-unicon/"


# A private homeowner is not a corporate reference. Their name does not belong
# on a public capability page, so it is shown as "Private client" instead.
PRIVATE = re.compile(r"^(dr|mr|mrs|ms|prof)[\s.&]|&\s*mrs|^house\s", re.IGNORECASE)


def client_name(n: str) -> str:
    return "Private client" if n and PRIVATE.search(n) else n


def e(x) -> str:
    return html.escape(str(x), quote=True)


def img(pair, cls, eager=False):
    src, alt = pair
    return (f'<img src="{RAW}{src}" alt="{e(alt)}" class="{cls}" '
            f'loading="{"eager" if eager else "lazy"}" decoding="async">')


# ------------------------------------------------------------------ the data
def load_projects():
    spec = importlib.util.spec_from_file_location("pp", os.path.join(ROOT, "tools", "projects_page.py"))
    pp = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(pp)
    rows = []
    for r in pp.DB:
        if pp.clean(r.get("Status")) in ("Cancelled", "Suspended"):
            continue
        rows.append({
            "name": pp.clean(r.get("Project Name")),
            "desc": pp.clean(r.get("Description")),
            "employer": client_name(pp.clean(r.get("Project Employer"))),
            "year": (pp.clean(r.get("Start")) or "")[:4],
            "months": pp.clean(r.get("Duration (M)")),
            "band": r.get("_band", ""),
            "status": pp.clean(r.get("Status")),
            "appointment": pp.clean(r.get("Appointment Type")),
            "contract": pp.clean(r.get("Contract Format")),
            "sector": pp.sector_of(r),
            "_t": " ".join([pp.clean(r.get("Project Name")), pp.clean(r.get("Description")),
                            pp.clean(r.get("Project Keywords"))]).lower(),
        })
    return rows


def select(rows, sel):
    """Pick the projects that count as evidence for a page."""
    out = []
    for r in rows:
        if sel.get("exclude") and any(w in r["_t"] for w in sel["exclude"]):
            continue
        hit = False
        if sel.get("sectors") and r["sector"] in sel["sectors"]:
            hit = True
        if sel.get("employers") and r["employer"] in sel["employers"]:
            hit = True
        if sel.get("any") and any(w in r["_t"] for w in sel["any"]):
            hit = True
        if hit:
            out.append(r)
    out.sort(key=lambda r: (r["year"] or "0000"), reverse=True)
    return out


# --------------------------------------------------------------- render bits
def hero(slug, c):
    return f'''    <header class="relative overflow-hidden border-b border-unicon-border bg-blueprint pb-16 pt-20 md:pb-24 md:pt-28">
        <div class="absolute inset-0 z-0">
            {img(HERO_IMG[slug], "h-full w-full object-cover opacity-10 grayscale", eager=True)}
            <div class="absolute inset-0 bg-gradient-to-t from-white via-white/85 to-transparent"></div>
        </div>
        <div class="animate-fade-up relative z-10 mx-auto max-w-[90rem] px-6 sm:px-8 lg:px-12">
            <div class="mb-8 flex flex-wrap items-center gap-3 font-mono text-[10px] uppercase tracking-widest">
                <a href="{BASE}/build.html" target="_top" class="text-gray-500 transition-colors hover:text-unicon-green">
                    <i class="fa-solid fa-arrow-left mr-2"></i>{e(c["eyebrow"])}
                </a>
                <span class="text-gray-400">/</span>
                <span class="bg-unicon-black px-3 py-1 text-white">{e(c["h1"][0].rstrip("&"))} {e(c["h1"][1].rstrip("."))}</span>
            </div>
            <h1 class="mb-8 text-5xl font-extrabold uppercase leading-[0.85] tracking-tighter sm:text-7xl lg:text-[7rem]">
                {c["h1"][0]} <br><span class="text-outline">{c["h1"][1]}</span>
            </h1>
            <div class="grid grid-cols-1 gap-10 border-t border-unicon-border pt-10 lg:grid-cols-12">
                <div class="lg:col-span-8">
                    <p class="max-w-3xl text-xl font-light leading-relaxed text-gray-700 md:text-2xl">{c["lead"]}</p>
                </div>
            </div>
        </div>
    </header>'''


def intro(c):
    paras = "\n".join(f'                    <p class="mt-5 text-base font-light leading-relaxed text-gray-700 md:text-lg">{p}</p>'
                      for p in c["intro"])
    return f'''    <section class="border-b border-unicon-border bg-white py-16 md:py-24">
        <div class="mx-auto max-w-[90rem] px-6 sm:px-8 lg:px-12">
            <div class="grid grid-cols-1 gap-12 lg:grid-cols-12 lg:gap-16">
                <div class="lg:col-span-5">
                    <p class="mb-3 font-mono text-[10px] uppercase tracking-widest text-unicon-green">The Discipline</p>
                    <h2 class="text-3xl font-extrabold uppercase leading-none tracking-tight sm:text-4xl md:text-5xl">
                        {c["intro_heading"][0]} <br><span class="text-unicon-green">{c["intro_heading"][1]}</span>
                    </h2>
                </div>
                <div class="lg:col-span-7">
{paras}
                </div>
            </div>
        </div>
    </section>'''


def scope(c):
    cards = ""
    for g in c["scope"]:
        items = "".join(f'<li class="flex gap-3"><i class="fa-solid fa-check mt-1 text-[10px] text-unicon-green"></i>'
                        f'<span>{i}</span></li>' for i in g["items"])
        cards += f'''
                <div class="border border-unicon-border bg-white p-8">
                    <i class="fa-solid {g["icon"]} mb-5 text-2xl text-unicon-green"></i>
                    <h3 class="mb-5 text-lg font-bold uppercase tracking-tight text-unicon-black">{g["title"]}</h3>
                    <ul class="space-y-2.5 text-sm font-light leading-relaxed text-gray-600">{items}</ul>
                </div>'''
    return f'''    <section id="scope" class="scroll-mt-24 border-b border-unicon-border bg-unicon-slate py-16 md:py-24">
        <div class="mx-auto max-w-[90rem] px-6 sm:px-8 lg:px-12">
            <div class="mb-12 max-w-3xl">
                <p class="mb-3 font-mono text-[10px] uppercase tracking-widest text-unicon-green">Scope Of Works</p>
                <h2 class="text-3xl font-extrabold uppercase leading-none tracking-tight sm:text-4xl md:text-5xl">{c["scope_heading"]}</h2>
                <p class="mt-6 text-base font-light leading-relaxed text-gray-600 md:text-lg">{c["scope_intro"]}</p>
            </div>
            <div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">{cards}
            </div>
        </div>
    </section>'''


def record(slug, c, picked, all_rows):
    """The evidence section - entirely derived from the project database."""
    n = len(picked)
    years = sorted({r["year"] for r in picked if r["year"]})
    clients = Counter(r["employer"] for r in picked
                      if r["employer"] and r["employer"] != "Private client")
    note = c.get("evidence_note")

    if not n:
        body = f'''
                <div class="border border-unicon-border bg-white p-8 md:p-12">
                    <p class="mb-4 font-mono text-[10px] uppercase tracking-widest text-unicon-green">Track Record</p>
                    <h3 class="mb-5 text-2xl font-extrabold uppercase tracking-tight text-unicon-black md:text-3xl">No Delivered Projects In This Sector Yet.</h3>
                    <p class="max-w-3xl text-sm font-light leading-relaxed text-gray-600 md:text-base">{note}</p>
                    <a href="{BASE}/projects.html" target="_top" class="mt-8 inline-block border border-unicon-black px-6 py-3 text-[10px] font-bold uppercase tracking-widest text-unicon-black transition-colors hover:bg-unicon-black hover:text-white">
                        See the full project database
                    </a>
                </div>'''
        return f'''    <section id="record" class="scroll-mt-24 border-b border-unicon-border bg-white py-16 md:py-24">
        <div class="mx-auto max-w-[90rem] px-6 sm:px-8 lg:px-12">{body}
        </div>
    </section>'''

    span = f"{years[0]}&ndash;{years[-1]}" if len(years) > 1 else (years[0] if years else "&mdash;")
    longest = max((int(r["months"]) for r in picked if str(r["months"]).isdigit()), default=0)
    stats = [(str(n), "Projects delivered"), (span, "Years active"),
             (str(len(clients)), "Client organisations"),
             (f"{longest} months" if longest else "&mdash;", "Longest contract")]
    stat_html = "".join(f'''
                    <div class="border-l-2 border-unicon-green pl-5">
                        <p class="text-3xl font-extrabold tracking-tighter text-unicon-black md:text-4xl">{v}</p>
                        <p class="mt-1 font-mono text-[9px] uppercase tracking-widest text-gray-500">{k}</p>
                    </div>''' for v, k in stats)

    rows = "".join(f'''
                        <tr class="border-b border-unicon-border last:border-0">
                            <td class="py-3 pr-4 font-mono text-[11px] text-gray-500">{e(r["year"])}</td>
                            <td class="py-3 pr-4 text-sm font-bold uppercase tracking-tight text-unicon-black">{e(r["name"])}</td>
                            <td class="py-3 pr-4 text-xs font-light text-gray-600">{e(r["employer"])}</td>
                            <td class="py-3 text-right font-mono text-[10px] uppercase tracking-widest text-unicon-green">{e(r["band"])}</td>
                        </tr>''' for r in picked[:12])

    top = "".join(f'<span class="border border-unicon-border bg-white px-3 py-1.5 text-[10px] font-bold uppercase '
                  f'tracking-widest text-gray-600">{e(a)} <span class="text-unicon-green">&times;{b}</span></span>'
                  for a, b in clients.most_common(8))

    note_html = (f'<p class="mt-6 max-w-3xl text-sm font-light leading-relaxed text-gray-600">{note}</p>'
                 if note else "")
    more = (f'<p class="mt-4 text-xs font-light text-gray-500">Showing the twelve most recent of {n}. '
            f'<a href="{BASE}/projects.html" target="_top" class="font-bold text-unicon-green hover:underline">'
            f'The full database is searchable here.</a></p>' if n > 12 else "")

    return f'''    <section id="record" class="scroll-mt-24 border-b border-unicon-border bg-white py-16 md:py-24">
        <div class="mx-auto max-w-[90rem] px-6 sm:px-8 lg:px-12">
            <div class="mb-12 max-w-3xl">
                <p class="mb-3 font-mono text-[10px] uppercase tracking-widest text-unicon-green">Track Record</p>
                <h2 class="text-3xl font-extrabold uppercase leading-none tracking-tight sm:text-4xl md:text-5xl">What We Have Actually Built.</h2>
                <p class="mt-6 text-base font-light leading-relaxed text-gray-600 md:text-lg">
                    Straight from our project database, not a brochure. Contract values are shown as bands.
                </p>{note_html}
            </div>
            <div class="mb-12 grid grid-cols-2 gap-8 lg:grid-cols-4">{stat_html}
            </div>
            <div class="grid grid-cols-1 gap-10 lg:grid-cols-12 lg:gap-14">
                <div class="lg:col-span-8">
                    <div class="overflow-x-auto border border-unicon-border bg-white p-6 md:p-8">
                        <table class="w-full min-w-[34rem] border-collapse text-left">
                            <thead>
                                <tr class="border-b-2 border-unicon-black">
                                    <th class="pb-3 pr-4 font-mono text-[9px] uppercase tracking-widest text-gray-500">Year</th>
                                    <th class="pb-3 pr-4 font-mono text-[9px] uppercase tracking-widest text-gray-500">Project</th>
                                    <th class="pb-3 pr-4 font-mono text-[9px] uppercase tracking-widest text-gray-500">Client</th>
                                    <th class="pb-3 text-right font-mono text-[9px] uppercase tracking-widest text-gray-500">Value</th>
                                </tr>
                            </thead>
                            <tbody>{rows}
                            </tbody>
                        </table>
                    </div>
                    {more}
                </div>
                <div class="lg:col-span-4">
                    <p class="mb-4 font-mono text-[10px] uppercase tracking-widest text-unicon-green">Who We Build For</p>
                    <div class="flex flex-wrap gap-2">{top}</div>
                    <div class="mt-8 overflow-hidden border border-unicon-border">
                        {img(MID_IMG[slug], "h-56 w-full object-cover")}
                    </div>
                </div>
            </div>
        </div>
    </section>'''


def method(c):
    steps = "".join(f'''
                <div class="flex gap-6 border-t border-unicon-border pt-8">
                    <span class="shrink-0 font-mono text-2xl font-bold text-unicon-green">{s["n"]}</span>
                    <div>
                        <h3 class="mb-2 font-bold uppercase tracking-tight text-unicon-black">{s["t"]}</h3>
                        <p class="text-sm font-light leading-relaxed text-gray-600 md:text-base">{s["d"]}</p>
                    </div>
                </div>''' for s in c["method"])
    return f'''    <section class="border-b border-unicon-border bg-unicon-slate py-16 md:py-24">
        <div class="mx-auto max-w-[90rem] px-6 sm:px-8 lg:px-12">
            <div class="mb-12 max-w-3xl">
                <p class="mb-3 font-mono text-[10px] uppercase tracking-widest text-unicon-green">Method</p>
                <h2 class="text-3xl font-extrabold uppercase leading-none tracking-tight sm:text-4xl md:text-5xl">{c["method_heading"]}</h2>
            </div>
            <div class="grid grid-cols-1 gap-8 md:grid-cols-2 md:gap-x-14">{steps}
            </div>
        </div>
    </section>'''


def capacity(c, all_rows):
    plant = "".join(f'<li class="flex gap-3 border-b border-unicon-border pb-3 last:border-0">'
                    f'<i class="fa-solid fa-gear mt-1 text-[10px] text-unicon-green"></i><span>{p}</span></li>'
                    for p in c["plant"])
    appt = Counter(r["appointment"] for r in all_rows if r["appointment"])
    forms = Counter(re.sub(r"\s*(19|20)\d\d$", "", r["contract"]).strip()
                    for r in all_rows if r["contract"])
    appt_html = "".join(f'<li class="flex justify-between gap-4 border-b border-gray-700 py-2.5">'
                        f'<span class="text-gray-300">{e(a)}</span>'
                        f'<span class="font-mono text-unicon-green">{b}</span></li>'
                        for a, b in appt.most_common())
    form_html = "".join(f'<li class="flex justify-between gap-4 border-b border-gray-700 py-2.5">'
                        f'<span class="text-gray-300">{e(a)}</span>'
                        f'<span class="font-mono text-unicon-green">{b}</span></li>'
                        for a, b in forms.most_common(4))
    return f'''    <section class="border-b border-unicon-border bg-white py-16 md:py-24">
        <div class="mx-auto max-w-[90rem] px-6 sm:px-8 lg:px-12">
            <div class="grid grid-cols-1 gap-12 lg:grid-cols-2 lg:gap-16">
                <div>
                    <p class="mb-3 font-mono text-[10px] uppercase tracking-widest text-unicon-green">Capacity</p>
                    <h2 class="mb-6 text-3xl font-extrabold uppercase leading-none tracking-tight sm:text-4xl">Plant &amp; Teams.</h2>
                    <p class="mb-8 text-base font-light leading-relaxed text-gray-600">
                        We self-perform the work that carries the risk and subcontract the rest to an approved
                        vendor list. What follows is the plant and capability this discipline draws on.
                    </p>
                    <ul class="space-y-3 border-t border-unicon-border pt-6 text-sm font-light text-gray-600">{plant}</ul>
                    <a href="{BASE}/contact/supplier-network.html" target="_top" class="mt-8 inline-block border border-unicon-black px-6 py-3 text-[10px] font-bold uppercase tracking-widest text-unicon-black transition-colors hover:bg-unicon-black hover:text-white">
                        Supply to our sites
                    </a>
                </div>
                <div>
                    <p class="mb-3 font-mono text-[10px] uppercase tracking-widest text-unicon-green">Contracting</p>
                    <h2 class="mb-6 text-3xl font-extrabold uppercase leading-none tracking-tight sm:text-4xl">How We Are Appointed.</h2>
                    <p class="mb-8 text-base font-light leading-relaxed text-gray-600">
                        Counts below are across the whole portfolio and come from the same database as the
                        project record above.
                    </p>
                    <div class="bg-unicon-black p-8 text-white md:p-10">
                        <p class="mb-4 font-mono text-[9px] uppercase tracking-widest text-gray-400">Appointment Type</p>
                        <ul class="mb-8 text-sm font-light">{appt_html}</ul>
                        <p class="mb-4 font-mono text-[9px] uppercase tracking-widest text-gray-400">Contract Form</p>
                        <ul class="text-sm font-light">{form_html}</ul>
                        <p class="mt-8 text-xs font-light leading-relaxed text-gray-400">
                            CIDB 7CE and 7GB. B-BBEE Level 2 contributor. Work is measured and constructed to
                            the SANS 1200 and SANS 2001 series, with building work to SANS 10400.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>'''


def related(c):
    cards = "".join(f'''
                <a href="{BASE}/{p}" target="_top" class="group border border-unicon-border bg-white p-8 transition-colors hover:border-unicon-green">
                    <h3 class="mb-2 font-bold uppercase tracking-tight text-unicon-black group-hover:text-unicon-green">{t}</h3>
                    <p class="text-sm font-light leading-relaxed text-gray-600">{d}</p>
                    <span class="mt-5 inline-block font-mono text-[9px] uppercase tracking-widest text-unicon-green">Open <i class="fa-solid fa-arrow-right ml-1"></i></span>
                </a>''' for t, p, d in c["related"])
    return f'''    <section class="border-b border-unicon-border bg-unicon-slate py-16 md:py-24">
        <div class="mx-auto max-w-[90rem] px-6 sm:px-8 lg:px-12">
            <div class="mb-12 max-w-3xl">
                <p class="mb-3 font-mono text-[10px] uppercase tracking-widest text-unicon-green">Alongside This</p>
                <h2 class="text-3xl font-extrabold uppercase leading-none tracking-tight sm:text-4xl md:text-5xl">Related Capability.</h2>
            </div>
            <div class="grid grid-cols-1 gap-6 md:grid-cols-3">{cards}
            </div>
        </div>
    </section>'''


def cta(c):
    h, p, b = c["cta"]
    return f'''    <section class="bg-unicon-green bg-blueprint-dark py-20 text-white">
        <div class="mx-auto flex max-w-[90rem] flex-col items-center justify-between gap-8 px-6 sm:px-8 md:flex-row lg:px-12">
            <div>
                <h2 class="mb-2 text-2xl font-extrabold uppercase tracking-tight text-unicon-black sm:text-3xl">{h}</h2>
                <p class="max-w-xl text-sm font-light text-white/90">{p}</p>
            </div>
            <div class="flex w-full flex-col gap-4 sm:flex-row md:w-auto">
                <a href="{BASE}/contact.html" target="_top" class="whitespace-nowrap border border-unicon-black bg-unicon-black px-8 py-4 text-center text-xs font-bold uppercase tracking-widest text-white shadow-xl transition-all hover:bg-white hover:text-unicon-black">
                    <i class="fa-solid fa-paper-plane mr-2"></i>{b}
                </a>
                <a href="{BASE}/projects.html" target="_top" class="whitespace-nowrap border border-unicon-black px-8 py-4 text-center text-xs font-bold uppercase tracking-widest text-unicon-black transition-all hover:bg-unicon-black hover:text-white">
                    <i class="fa-solid fa-database mr-2"></i>Project Database
                </a>
            </div>
        </div>
    </section>'''



HUB_START = "<!-- BUILD:HUB:START - generated by tools/build_pages.py, do not edit by hand -->"
HUB_END = "<!-- BUILD:HUB:END -->"

HUB_BLURB = {
    "water-engineering": ("Bulk Water & Wastewater", "fa-water",
        "Reservoirs, treatment works, pump stations and pipelines. The largest part of what we do."),
    "civil-engineering": ("Heavy Civils", "fa-bridge",
        "Provincial bridges, river crossings, canals, roads and mass earthworks."),
    "structural-engineering": ("Structural Concrete", "fa-cube",
        "Post-tensioned walls, domes, suspended slabs and the formwork behind them."),
    "general-building": ("General Building", "fa-building",
        "Retail centres, schools, clinics, offices and homes, platform to practical completion."),
    "industrial-logistics": ("Industrial & Logistics", "fa-industry",
        "Factories, depots, heavy floors, machine foundations and hardstands."),
    "agricultural-engineering": ("Agricultural EPC", "fa-tractor",
        "Abattoirs, dairies, farm water, irrigation and farm infrastructure."),
    "mining-infrastructure": ("Mining & Heavy Industry", "fa-helmet-safety",
        "Water storage, pipelines and heavy foundations on operating sites."),
    "renewable-energy": ("Renewable Energy Civils", "fa-solar-panel",
        "Balance-of-plant scope: platforms, foundations, hardstands and access."),
}


def hub(content, rows) -> str:
    cards = ""
    for slug, c in content.items():
        if slug.startswith("_"):
            continue
        title, icon, blurb = HUB_BLURB[slug]
        n = len(select(rows, c["select"]))
        tag = (f'<span class="font-mono text-[9px] uppercase tracking-widest text-unicon-green">'
               f'{n} project{"s" if n != 1 else ""} delivered</span>' if n else
               '<span class="font-mono text-[9px] uppercase tracking-widest text-gray-400">Capability, no delivered projects yet</span>')
        cards += f'''
                <a href="{BASE}/build/{slug}.html" target="_top" class="group flex flex-col border border-unicon-border bg-white p-8 transition-colors hover:border-unicon-green">
                    <i class="fa-solid {icon} mb-5 text-2xl text-unicon-green"></i>
                    <h3 class="mb-2 text-lg font-bold uppercase tracking-tight text-unicon-black group-hover:text-unicon-green">{title}</h3>
                    <p class="mb-5 flex-grow text-sm font-light leading-relaxed text-gray-600">{blurb}</p>
                    {tag}
                </a>'''
    total = len(rows)
    return f'''    <section class="border-b border-unicon-border bg-unicon-slate py-16 md:py-24">
        <div class="mx-auto max-w-[90rem] px-6 sm:px-8 lg:px-12">
            <div class="mb-12 max-w-3xl">
                <p class="mb-3 font-mono text-[10px] uppercase tracking-widest text-unicon-green">The Build Division</p>
                <h2 class="text-3xl font-extrabold uppercase leading-none tracking-tight sm:text-4xl md:text-5xl">Eight Disciplines, One Contractor.</h2>
                <p class="mt-6 text-base font-light leading-relaxed text-gray-600 md:text-lg">
                    {total} projects delivered since 1991. Each page below sets out the scope our teams
                    execute, the method we use and the projects behind it &mdash; drawn from the project
                    database rather than written for a brochure. Where we have not built in a sector yet,
                    the page says so.
                </p>
            </div>
            <div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">{cards}
            </div>
        </div>
    </section>'''


def body(slug, c, rows):
    picked = select(rows, c["select"])
    return "\n\n".join([hero(slug, c), intro(c), scope(c), record(slug, c, picked, rows),
                        method(c), capacity(c, rows), related(c), cta(c)])


def install_markers(s: str) -> str:
    i = s.index(NAV_END) + len(NAV_END)
    j = s.index(FOOT_START)
    return s[:i] + "\n\n    " + START + "\n" + END + "\n\n    " + s[j:]


def main() -> None:
    cmd = sys.argv[1] if len(sys.argv) > 1 else "build"
    content = json.load(open(DATA, encoding="utf-8"))
    rows = load_projects()
    changed = []
    for slug, c in content.items():
        if slug.startswith("_"):
            continue
        path = os.path.join(ROOT, "build", slug + ".html")
        s = old = open(path, encoding="utf-8").read()
        if START not in s:
            s = install_markers(s)
        s = re.sub(re.escape(START) + r".*?" + re.escape(END),
                   lambda _m: START + "\n" + body(slug, c, rows) + "\n    " + END, s, flags=re.S)
        if s != old:
            changed.append(slug)
            if cmd != "check":
                open(path, "w", encoding="utf-8").write(s)

    # the Build hub page indexes all eight
    hub_path = os.path.join(ROOT, "build.html")
    hs = ho = open(hub_path, encoding="utf-8").read()
    hs = re.sub(re.escape(HUB_START) + r".*?" + re.escape(HUB_END),
                lambda _m: HUB_START + "\n" + hub(content, rows) + "\n    " + HUB_END, hs, flags=re.S)
    if hs != ho:
        changed.append("build.html (hub)")
        if cmd != "check":
            open(hub_path, "w", encoding="utf-8").write(hs)

    if cmd == "check":
        if changed:
            print("These Build pages are out of date. Run 'python3 tools/build_pages.py build':",
                  file=sys.stderr)
            for x in changed:
                print("  -", x, file=sys.stderr)
            sys.exit(1)
        print(f"{len(content) - 1} Build pages are current.")
    else:
        for slug, c in content.items():
            if slug.startswith("_"):
                continue
            picked = select(rows, c["select"])
            print(f"  {slug:<28} {len(picked):>3} project(s) of evidence"
                  + ("  [no delivered work - evidence note shown]" if not picked else ""))
        print(f"{len(changed)} page(s) written.")


if __name__ == "__main__":
    main()
