#!/usr/bin/env python3
"""Render job openings onto the careers page.

Openings live in tools/careers.json. This writes them into
contact/join-unicon.html between markers, and emits a JobPosting structured
data block for each live role so the listing is eligible for Google's job
results. With no openings it renders a no-current-openings state instead,
which is the honest thing to show and still gives a candidate somewhere to go.

Usage:
    python3 tools/careers.py build     regenerate the openings section
    python3 tools/careers.py check     validate the data (exit 1 on problems)
"""
from __future__ import annotations

import html
import json
import os
import re
import sys
from datetime import date, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "tools", "careers.json")
PAGE = os.path.join(ROOT, "contact", "join-unicon.html")
BASE = "https://www.uniconsa.co.za"
PAGE_URL = f"{BASE}/contact/join-unicon.html"

START = "<!-- CAREERS:OPENINGS:START - generated by tools/careers.py, do not edit by hand -->"
END = "<!-- CAREERS:OPENINGS:END -->"
LD_START = "<!-- CAREERS:SCHEMA:START - generated by tools/careers.py, do not edit by hand -->"
LD_END = "<!-- CAREERS:SCHEMA:END -->"

VALID_TYPES = ("FULL_TIME", "PART_TIME", "CONTRACTOR", "TEMPORARY", "INTERN")
REQUIRED = ("id", "title", "discipline", "location", "type", "posted", "summary")


def e(s) -> str:
    return html.escape(str(s), quote=True)


def load() -> list[dict]:
    return json.load(open(DATA, encoding="utf-8")).get("openings", [])


def validate(openings: list[dict]) -> list[str]:
    problems, seen = [], set()
    for i, o in enumerate(openings):
        label = o.get("id") or f"opening[{i}]"
        for f in REQUIRED:
            if not o.get(f):
                problems.append(f"{label}: missing '{f}'")
        if o.get("id") in seen:
            problems.append(f"{label}: duplicate id")
        seen.add(o.get("id"))
        if o.get("type") and o["type"] not in VALID_TYPES:
            problems.append(f"{label}: type must be one of {VALID_TYPES}")
        for f in ("posted", "closes"):
            v = o.get(f)
            if v and not re.fullmatch(r"\d{4}-\d{2}-\d{2}", v):
                problems.append(f"{label}: {f} must be YYYY-MM-DD, got {v!r}")
        if o.get("closes") and o.get("posted") and o["closes"] < o["posted"]:
            problems.append(f"{label}: closes is before posted")
    return problems


def live(openings: list[dict]) -> list[dict]:
    """Drop anything already past its closing date."""
    today = date.today().isoformat()
    return [o for o in openings if not o.get("closes") or o["closes"] >= today]


def fmt(iso: str) -> str:
    return datetime.strptime(iso, "%Y-%m-%d").strftime("%d %B %Y").lstrip("0")


# ----------------------------------------------------------------- render

def empty_state() -> str:
    return f"""
                <div class="border border-unicon-border bg-unicon-slate p-8 md:p-12 text-center">
                    <p class="font-mono text-[10px] uppercase tracking-widest text-unicon-green mb-4">Current Openings</p>
                    <h3 class="text-2xl md:text-3xl font-extrabold uppercase tracking-tight text-unicon-black mb-4">No Positions Are Open Right Now.</h3>
                    <p class="mx-auto max-w-2xl text-sm md:text-base font-light leading-relaxed text-gray-600">
                        We advertise here first, and only when a role genuinely exists. Rather than
                        list vacancies we cannot fill, this page stays empty until we are hiring.
                    </p>
                    <p class="mx-auto mt-4 max-w-2xl text-sm md:text-base font-light leading-relaxed text-gray-600">
                        You are still welcome to introduce yourself. We keep speculative applications
                        on file and revisit them when a site or a discipline needs someone, so a
                        considered introduction now is often how people end up joining.
                    </p>
                    <a href="#how-to-apply" class="mt-8 inline-block bg-unicon-green px-8 py-4 text-[10px] font-bold uppercase tracking-widest text-white transition-colors hover:bg-unicon-black">
                        How to introduce yourself
                    </a>
                </div>"""


def card(o: dict) -> str:
    closes = (f'<span class="text-gray-500">Closes {e(fmt(o["closes"]))}</span>'
              if o.get("closes") else '<span class="text-gray-500">Open until filled</span>')
    reqs = "".join(f"<li>{e(r)}</li>" for r in o.get("requirements", []))
    resp = "".join(f"<li>{e(r)}</li>" for r in o.get("responsibilities", []))
    blocks = ""
    if resp:
        blocks += f"""
                        <div class="mt-6">
                            <p class="mb-2 font-mono text-[9px] uppercase tracking-widest text-unicon-green">The role</p>
                            <ul class="space-y-1.5 text-sm font-light text-gray-600">{resp}</ul>
                        </div>"""
    if reqs:
        blocks += f"""
                        <div class="mt-6">
                            <p class="mb-2 font-mono text-[9px] uppercase tracking-widest text-unicon-green">What we need to see</p>
                            <ul class="space-y-1.5 text-sm font-light text-gray-600">{reqs}</ul>
                        </div>"""
    return f"""
                <article id="{e(o['id'])}" class="border border-unicon-border bg-white p-8 md:p-10 transition-colors hover:border-unicon-green">
                    <div class="mb-4 flex flex-wrap items-center gap-3 font-mono text-[9px] uppercase tracking-widest">
                        <span class="bg-unicon-green px-3 py-1 text-white">{e(o['discipline'])}</span>
                        <span class="text-gray-500">{e(o['location'])}</span>
                        <span class="text-gray-500">{e(o['type'].replace('_', ' ').title())}</span>
                        {closes}
                    </div>
                    <h3 class="text-2xl font-extrabold uppercase tracking-tight text-unicon-black">{e(o['title'])}</h3>
                    <p class="mt-3 text-sm md:text-base font-light leading-relaxed text-gray-600">{e(o['summary'])}</p>{blocks}
                    <a href="#how-to-apply" class="mt-8 inline-block border border-unicon-black px-6 py-3 text-[10px] font-bold uppercase tracking-widest text-unicon-black transition-colors hover:bg-unicon-black hover:text-white">
                        Apply for this role
                    </a>
                </article>"""


def openings_html(items: list[dict]) -> str:
    if not items:
        return empty_state()
    head = f"""
                <div class="mb-8">
                    <p class="font-mono text-[10px] uppercase tracking-widest text-unicon-green mb-3">Current Openings</p>
                    <h3 class="text-2xl md:text-3xl font-extrabold uppercase tracking-tight text-unicon-black">
                        {len(items)} position{'s' if len(items) != 1 else ''} open
                    </h3>
                </div>
                <div class="grid grid-cols-1 gap-6">"""
    return head + "".join(card(o) for o in items) + "\n                </div>"


def schema_html(items: list[dict]) -> str:
    if not items:
        return ""
    out = []
    for o in items:
        d = {
            "@context": "https://schema.org",
            "@type": "JobPosting",
            "title": o["title"],
            "description": o["summary"],
            "identifier": {"@type": "PropertyValue", "name": "Unicon Construction", "value": o["id"]},
            "datePosted": o["posted"],
            "employmentType": o["type"],
            "hiringOrganization": {
                "@type": "Organization", "name": "Unicon Construction", "sameAs": BASE + "/",
                "logo": "https://raw.githubusercontent.com/chrisnott-unicon/UniconLogo/main/UniconBlk.png"},
            "jobLocation": {"@type": "Place", "address": {
                "@type": "PostalAddress", "addressLocality": o["location"],
                "addressCountry": "ZA"}},
            "directApply": False,
            "url": f"{PAGE_URL}#{o['id']}",
        }
        if o.get("closes"):
            d["validThrough"] = o["closes"]
        out.append('    <script type="application/ld+json">\n'
                   + json.dumps(d, indent=2, ensure_ascii=False) + "\n    </script>")
    return "\n" + "\n".join(out) + "\n"


def replace(src: str, start: str, end: str, body: str) -> str:
    if start not in src or end not in src:
        raise SystemExit(f"contact/join-unicon.html is missing markers:\n  {start}\n  {end}")
    return re.sub(re.escape(start) + r".*?" + re.escape(end),
                  lambda _m: start + body + "\n" + " " * (16 if start == START else 4) + end,
                  src, flags=re.S)


def main() -> None:
    cmd = sys.argv[1] if len(sys.argv) > 1 else "build"
    openings = load()
    problems = validate(openings)
    if problems:
        print("Careers data problems:", file=sys.stderr)
        for p in problems:
            print("  -", p, file=sys.stderr)
        sys.exit(1)

    shown = live(openings)
    expired = len(openings) - len(shown)

    if cmd == "check":
        print(f"{len(openings)} opening(s) defined, {len(shown)} live"
              + (f", {expired} past closing date" if expired else "") + ".")
        for o in shown:
            print(f"  {o['id']:<24} {o['title'][:44]:<44} {o['location']}")
        return

    src = open(PAGE, encoding="utf-8").read()
    new = replace(src, START, END, openings_html(shown))
    new = replace(new, LD_START, LD_END, schema_html(shown))
    if new != src:
        open(PAGE, "w", encoding="utf-8").write(new)
        print(f"careers page updated: {len(shown)} opening(s) rendered.")
    else:
        print("Already up to date.")


if __name__ == "__main__":
    main()
