#!/usr/bin/env python3
"""Own the shared chrome - navigation, mobile menu and footer - for every page.

Before this existed the site carried six different top-level menus. The Build
sub-pages had no Contact link, the Manage sub-pages had a three-item menu, and
only the project archives had a Portfolio link, so from the home page there was
no way to reach the project database from the navigation at all. Twenty-seven
structurally different navs and twenty different footers had drifted apart.

This generates one nav and one footer and writes them into every page between
markers, so they cannot drift again.

Usage:
    python3 tools/chrome.py build     rewrite the chrome on every page
    python3 tools/chrome.py check     fail if any page is out of date
    python3 tools/chrome.py init      install the markers (one time)
"""
from __future__ import annotations

import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = "https://www.uniconsa.co.za"

NAV_START = "<!-- CHROME:NAV:START - generated by tools/chrome.py, do not edit by hand -->"
NAV_END = "<!-- CHROME:NAV:END -->"
FOOT_START = "<!-- CHROME:FOOTER:START - generated by tools/chrome.py, do not edit by hand -->"
FOOT_END = "<!-- CHROME:FOOTER:END -->"

# ------------------------------------------------------------------ the menu
# (label, hub page, [(sub-label, sub page), ...])
MENU = [
    ("Company", "home/about.html", [
        ("Profile", "home/about.html"),
        ("History & Legacy", "home/history.html"),
        ("Workforce", "home/team.html"),
        ("Core Ethos", "home/ethos.html"),
    ]),
    ("Design", "design.html", [
        ("Architectural Plan", "design/architecture.html"),
        ("Civil Profiling", "design/civil-engineering.html"),
        ("Structural & MEP", "design/structural-engineering.html"),
        ("BIM & Constructability", "design/constructability.html"),
    ]),
    ("Build", "build.html", [
        ("Bulk Water", "build/water-engineering.html"),
        ("Heavy Civils", "build/civil-engineering.html"),
        ("Structural Concrete", "build/structural-engineering.html"),
        ("Mining Civils", "build/mining-infrastructure.html"),
        ("Renewable Energy BoP", "build/renewable-energy.html"),
        ("Ports & Logistics", "build/industrial-logistics.html"),
        ("Agricultural EPC", "build/agricultural-engineering.html"),
        ("General Building", "build/general-building.html"),
    ]),
    ("Manage", "manage.html", [
        ("Project Management", "manage/project-management.html"),
        ("Facility Management", "manage/facility-management.html"),
    ]),
    ("Portfolio", "projects.html", [
        ("Project Database", "projects.html"),
        ("2020s & Active", "projects/2020s-&-active-projects.html"),
        ("2010s Archive", "projects/2010s-archive.html"),
        ("2000s Archive", "projects/2000s-archive.html"),
        ("1990s Archive", "projects/1990s-archive.html"),
        ("Photo Gallery", "projects/photo-gallery.html"),
    ]),
    ("Insights", "communications/insights.html", []),
    ("Contact", "contact.html", [
        ("Get In Touch", "contact.html"),
        ("Olive CPM", "contact/olive-cpm-overview.html"),
        ("Vendor Network", "contact/supplier-network.html"),
        ("Careers", "contact/join-unicon.html"),
    ]),
]

FOOTER_SECTORS = [
    ("Bulk Water", "build/water-engineering.html"),
    ("Civils & Earthworks", "build/civil-engineering.html"),
    ("Commercial Building", "build/general-building.html"),
    ("Agricultural Build", "build/agricultural-engineering.html"),
    ("Mining Civils", "build/mining-infrastructure.html"),
]
FOOTER_COMPANY = [
    ("Our Projects", "projects.html"),
    ("Company History", "home/history.html"),
    ("Construction Tech", "design/constructability.html"),
    ("Insights & News", "communications/insights.html"),
    ("Vendor Network", "contact/supplier-network.html"),
    ("Careers", "contact/join-unicon.html"),
    ("Contact Us", "contact.html"),
]

LOGO = "https://raw.githubusercontent.com/chrisnott-unicon/UniconLogo/main/UniconBlk.png"
MAP = "https://share.google/XC0JuqEbN4XYJeM5k"
PHONE_HREF = "tel:+27664834709"
PHONE_TEXT = "+27 66 483 4709"

DROP_ITEM = ("block px-5 py-3 text-[10px] uppercase tracking-widest text-gray-400 "
             "hover:text-white hover:bg-unicon-green/20")
DROP_ACTIVE = ("block px-5 py-3 text-[10px] uppercase tracking-widest text-unicon-green "
               "bg-[#111111] hover:text-white")
TOP = "text-xs font-bold uppercase tracking-widest transition-colors py-2 flex items-center gap-1"


def u(p: str) -> str:
    return f"{BASE}/" + ("" if p == "index.html" else p)


def section_of(page: str) -> str | None:
    """Which top-level menu item owns this page."""
    for label, hub, subs in MENU:
        if page == hub or page in [s[1] for s in subs]:
            return label
    for label, hub, subs in MENU:                       # directory fallback
        d = os.path.dirname(hub)
        if d and page.startswith(d + "/"):
            return label
    return None


# ------------------------------------------------------------------- render
def nav(page: str) -> str:
    cur = section_of(page)
    out = [
        f'    <nav id="navbar" class="fixed top-0 left-0 w-full z-[100] transition-all duration-300 bg-[#0a0a0a]/95 backdrop-blur-md border-b border-gray-800 py-3 sm:py-4">',
        '        <div class="max-w-[90rem] mx-auto px-6 sm:px-8 lg:px-12 flex justify-between items-center">',
        f'            <a href="{u("index.html")}" target="_top" class="flex items-center gap-3 group relative z-[110]">',
        f'                <img src="{LOGO}" alt="Unicon Construction Logo" class="h-6 sm:h-8 w-auto invert brightness-0 transition-opacity group-hover:opacity-80">',
        '                <span class="font-extrabold text-xl sm:text-2xl tracking-tighter uppercase text-white group-hover:text-unicon-green transition-colors">UNICON</span>',
        '                <div class="h-4 w-[1px] bg-gray-700"></div>',
        '                <span class="text-[8px] sm:text-[10px] font-mono text-unicon-green tracking-[0.2em] uppercase font-bold hidden sm:inline-block">EST. 1991</span>',
        '            </a>',
        '',
        '            <!-- Desktop menu -->',
        '            <div class="hidden lg:flex items-center gap-6 xl:gap-8">',
    ]
    for label, hub, subs in MENU:
        colour = "text-unicon-green" if label == cur else "text-white hover:text-unicon-green"
        align = "right-0" if label == "Contact" else "left-0"
        width = "w-56" if label in ("Build", "Portfolio") else "w-52"
        if not subs:
            out.append('                <div class="relative group">')
            out.append(f'                    <a href="{u(hub)}" target="_top" class="{TOP} {colour}">{label}</a>')
            out.append('                </div>')
            continue
        out += [
            '                <div class="relative group">',
            f'                    <a href="{u(hub)}" target="_top" class="{TOP} {colour}">{label} <i class="fa-solid fa-chevron-down text-[9px] opacity-70"></i></a>',
            f'                    <div class="absolute top-full {align} mt-4 {width} bg-[#0a0a0a] border border-gray-800 shadow-2xl opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-300 translate-y-2 group-hover:translate-y-0">',
            f'                        <div class="absolute -top-4 {align} w-full h-4 bg-transparent"></div>',
        ]
        for i, (sl, sp) in enumerate(subs):
            cls = DROP_ACTIVE if sp == page else DROP_ITEM
            if i < len(subs) - 1:
                cls += " border-b border-gray-800"
            out.append(f'                        <a href="{u(sp)}" target="_top" class="{cls}">{sl}</a>')
        out += ['                    </div>', '                </div>']
    out += [
        '            </div>',
        '',
        '            <div class="flex items-center gap-4 relative z-[110]">',
        f'                <a href="{u("contact.html")}" target="_top" class="hidden sm:inline-block lg:hidden xl:inline-block rounded-sm bg-unicon-green px-5 py-2.5 text-[10px] font-bold uppercase tracking-widest text-white transition-colors hover:bg-white hover:text-unicon-black">Enquire</a>',
        '                <button id="mobile-menu-btn" class="lg:hidden text-white hover:text-unicon-green transition-colors p-2 focus:outline-none" aria-label="Toggle mobile menu" aria-expanded="false" aria-controls="mobile-menu">',
        '                    <i class="fa-solid fa-bars text-xl"></i>',
        '                </button>',
        '            </div>',
        '        </div>',
        '',
        '        <!-- Mobile menu -->',
        '        <div id="mobile-menu" class="fixed inset-y-0 right-0 w-80 max-w-[85vw] bg-[#0a0a0a] z-[1000] transform translate-x-full transition-transform duration-300 overflow-y-auto lg:hidden pt-24 pb-12 px-6 border-l border-gray-800 shadow-2xl flex flex-col justify-between">',
        '            <div class="flex flex-col space-y-6">',
    ]
    for label, hub, subs in MENU:
        out += [
            f'                <!-- {label} -->',
            '                <div>',
            f'                    <a href="{u(hub)}" target="_top" class="block text-unicon-green text-[10px] uppercase font-mono tracking-widest border-b border-gray-800 pb-2 mb-3 hover:text-white transition-colors">{label}</a>',
        ]
        if subs:
            out.append('                    <div class="flex flex-col space-y-3 pl-2">')
            for sl, sp in subs:
                c = "text-unicon-green" if sp == page else "text-white hover:text-unicon-green"
                out.append(f'                        <a href="{u(sp)}" target="_top" class="text-sm font-bold uppercase tracking-wide {c}">{sl}</a>')
            out.append('                    </div>')
        out.append('                </div>')
    out += [
        '            </div>',
        '            <div class="mt-8 border-t border-gray-800 pt-6">',
        f'                <a href="{u("contact.html")}" target="_top" class="block rounded-sm bg-unicon-green py-4 text-center text-xs font-bold uppercase tracking-widest text-white transition-colors hover:bg-white hover:text-unicon-black">Contact Us</a>',
        '            </div>',
        '        </div>',
        '    </nav>',
    ]
    return "\n".join(out)


def links(items, page):
    out = []
    for label, p in items:
        cls = "text-unicon-green" if p == page else "hover:text-unicon-green transition-colors link-underline"
        out.append(f'                        <li><a href="{u(p)}" target="_top" class="{cls}">{label}</a></li>')
    return "\n".join(out)


def footer(page: str) -> str:
    return f'''    <footer class="footer-container text-unicon-black pt-20 pb-10 border-t border-unicon-border relative overflow-hidden bg-white">
        <div class="max-w-[90rem] mx-auto px-6 sm:px-8 lg:px-12 relative z-10">
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-12 gap-12 lg:gap-16 mb-16">
                <div class="lg:col-span-4">
                    <div class="flex items-center gap-4 mb-8">
                        <img src="{LOGO}" alt="Unicon Construction Logo" class="h-10 md:h-12 w-auto">
                        <div class="h-6 w-[1px] bg-unicon-border ml-2"></div>
                        <span class="text-[10px] font-mono text-unicon-green tracking-[0.2em] uppercase font-bold">EST. 1991</span>
                    </div>
                    <p class="text-gray-500 text-sm font-light leading-relaxed mb-10 max-w-sm">
                        Uncompromising quality and engineering excellence in South Africa. Specialists in water retaining structures, civils, and turnkey construction.
                    </p>
                    <div class="bg-unicon-slate border border-unicon-border p-5 rounded-sm shadow-sm relative overflow-hidden group">
                        <div class="flex items-center justify-between mb-4">
                            <div class="flex items-center gap-2">
                                <div class="w-2 h-2 bg-unicon-green rounded-full"></div>
                                <span class="text-[10px] font-mono text-unicon-green uppercase tracking-widest font-bold">Head Office</span>
                            </div>
                            <span class="text-[8px] text-gray-400 font-mono tracking-widest uppercase">KWAZULU-NATAL</span>
                        </div>
                        <div class="grid grid-cols-2 gap-4 border-t border-white pt-4">
                            <div>
                                <p class="text-[8px] text-gray-400 uppercase font-mono mb-1">Completed Works</p>
                                <p class="text-xs font-bold text-unicon-black uppercase">92 Projects</p>
                            </div>
                            <div>
                                <p class="text-[8px] text-gray-400 uppercase font-mono mb-1">BBEEE Level</p>
                                <p class="text-xs font-bold text-unicon-black uppercase">Level 2</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="lg:col-span-2">
                    <h4 class="text-[10px] font-bold uppercase tracking-[0.2em] text-unicon-green mb-8 border-l-2 border-unicon-green pl-3">Sectors</h4>
                    <ul class="space-y-4 text-xs font-light text-gray-500">
{links(FOOTER_SECTORS, page)}
                    </ul>
                </div>
                <div class="lg:col-span-2">
                    <h4 class="text-[10px] font-bold uppercase tracking-[0.2em] text-unicon-green mb-8 border-l-2 border-unicon-green pl-3">Company</h4>
                    <ul class="space-y-4 text-xs font-light text-gray-500">
{links(FOOTER_COMPANY, page)}
                    </ul>
                </div>
                <div class="lg:col-span-4">
                    <h4 class="text-[10px] font-bold uppercase tracking-[0.2em] text-unicon-green mb-8 border-l-2 border-unicon-green pl-3">Head Office</h4>
                    <div class="space-y-6">
                        <div class="flex items-start gap-4">
                            <i class="fa-solid fa-location-crosshairs text-unicon-green mt-1 text-sm opacity-70"></i>
                            <div>
                                <p class="text-xs font-bold text-unicon-black uppercase tracking-tight">Hilton / Pietermaritzburg</p>
                                <p class="text-[10px] text-gray-500 font-light mt-1">KwaZulu-Natal, South Africa</p>
                                <a href="{MAP}" target="_blank" rel="noopener noreferrer" class="text-[9px] font-bold text-unicon-green uppercase tracking-widest mt-2 block hover:underline">View Map Location</a>
                            </div>
                        </div>
                        <div class="flex items-start gap-4">
                            <i class="fa-solid fa-phone-volume text-unicon-green mt-1 text-sm opacity-70"></i>
                            <div>
                                <p class="text-[10px] text-gray-400 uppercase tracking-widest font-mono mb-1">Direct Contact</p>
                                <a href="{PHONE_HREF}" class="text-xs font-bold text-unicon-black hover:text-unicon-green transition-colors font-mono tracking-tighter">{PHONE_TEXT}</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="pt-8 border-t border-unicon-border flex flex-col md:flex-row justify-between items-center gap-6">
                <div class="flex flex-wrap justify-center md:justify-start items-center gap-6">
                    <p class="text-[10px] text-gray-400 uppercase tracking-widest">&copy; <span id="year-footer"></span> Unicon Construction SA</p>
                    <div class="flex gap-3">
                        <span class="text-[8px] text-gray-400 uppercase tracking-widest border border-unicon-border px-2 py-0.5 rounded-sm bg-white">CIDB: 7CE // 7GB</span>
                        <span class="text-[8px] text-gray-400 uppercase tracking-widest border border-unicon-border px-2 py-0.5 rounded-sm bg-white">ISO 9001</span>
                    </div>
                </div>
                <div class="flex gap-6 items-center">
                    <div class="flex gap-4 items-center">
                        <a href="https://www.linkedin.com/company/unicon-construction" target="_blank" rel="noopener noreferrer" class="text-gray-400 hover:text-[#0a66c2] transition-colors" aria-label="Unicon Construction on LinkedIn">
                            <i class="fa-brands fa-linkedin text-xl"></i>
                        </a>
                        <a href="https://www.facebook.com/uniconconstruction" target="_blank" rel="noopener noreferrer" class="text-gray-400 hover:text-[#1877f2] transition-colors" aria-label="Unicon Construction on Facebook">
                            <i class="fa-brands fa-facebook text-xl"></i>
                        </a>
                    </div>
                    <div class="w-[1px] h-6 bg-gray-300 hidden sm:block"></div>
                    <p class="text-[9px] font-mono text-gray-400 uppercase tracking-tighter">
                        Quality <span class="text-unicon-green font-bold">Construction</span>
                    </p>
                </div>
            </div>
        </div>
    </footer>'''


# -------------------------------------------------------------------- apply
def balanced(s: str, i: int, tag: str) -> int:
    depth = 0
    for m in re.finditer(rf"<{tag}\b|</{tag}>", s[i:]):
        depth += -1 if m.group(0).startswith("</") else 1
        if depth == 0:
            return i + m.end()
    raise SystemExit(f"unbalanced <{tag}>")


def pages() -> list[str]:
    out = []
    for f in sorted(glob.glob(os.path.join(ROOT, "**", "*.html"), recursive=True)):
        rel = os.path.relpath(f, ROOT).replace(os.sep, "/")
        s = open(f, encoding="utf-8").read()
        if 'http-equiv="refresh"' in s or rel == "404.html":
            continue                                    # redirect stubs and the 404 keep their own markup
        out.append(rel)
    return out


def install_markers(s: str) -> str:
    """One-time: wrap the existing nav and footer in markers."""
    if NAV_START not in s and '<nav id="navbar"' in s:
        i = s.index('<nav id="navbar"')
        i = s.rfind("\n", 0, i) + 1
        j = balanced(s, i, "nav")
        s = s[:i] + NAV_START + "\n" + s[i:j] + "\n    " + NAV_END + s[j:]
    if FOOT_START not in s and "<footer" in s:
        i = s.index("<footer")
        i = s.rfind("\n", 0, i) + 1
        j = balanced(s, i, "footer")
        s = s[:i] + FOOT_START + "\n" + s[i:j] + "\n    " + FOOT_END + s[j:]
    return s


def replace(s: str, start: str, end: str, body: str) -> str:
    return re.sub(re.escape(start) + r".*?" + re.escape(end),
                  lambda _m: start + "\n" + body + "\n    " + end, s, flags=re.S)


def render(page: str, s: str) -> str:
    if NAV_START in s:
        s = replace(s, NAV_START, NAV_END, nav(page))
    if FOOT_START in s:
        s = replace(s, FOOT_START, FOOT_END, footer(page))
    return s


def main() -> None:
    cmd = sys.argv[1] if len(sys.argv) > 1 else "build"
    changed, missing = [], []
    for page in pages():
        path = os.path.join(ROOT, page)
        s = old = open(path, encoding="utf-8").read()
        if cmd == "init":
            s = install_markers(s)
        if NAV_START not in s or FOOT_START not in s:
            missing.append(page)
        s = render(page, s)
        if s != old:
            changed.append(page)
            if cmd != "check":
                open(path, "w", encoding="utf-8").write(s)

    if missing:
        print("Pages without chrome markers (run 'init'):", file=sys.stderr)
        for p in missing:
            print("  -", p, file=sys.stderr)
    if cmd == "check":
        if changed or missing:
            print(f"\n{len(changed)} page(s) have stale chrome. Run 'python3 tools/chrome.py build'.",
                  file=sys.stderr)
            for p in changed:
                print("  -", p, file=sys.stderr)
            sys.exit(1)
        print(f"chrome is current on {len(pages())} pages.")
    else:
        print(f"{cmd}: {len(changed)} page(s) updated, {len(pages())} checked.")
        if missing:
            sys.exit(1)


if __name__ == "__main__":
    main()
