#!/usr/bin/env python3
"""Render the data-driven sections of the home page.

The home page's proof sections — portfolio statistics, named clients, repeat
business and flagship projects — are generated from tools/portfolio.json so the
numbers cannot drift out of step with the project record. Everything else in
index.html is hand-written and left untouched.

Sections are written between HTML comment markers, so this is safe to re-run.

Usage:
    python3 tools/homepage.py build     regenerate the generated sections
    python3 tools/homepage.py check     verify markers and data are present
"""
from __future__ import annotations

import argparse
import html
import json
import os
import re
import sys
import urllib.parse
from datetime import datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "tools", "portfolio.json")
INDEX = os.path.join(ROOT, "index.html")
FEED = os.path.join(ROOT, "communications", "insights", "feed.xml")
BASE = "https://www.uniconsa.co.za"
PHOTOS = "raw.githubusercontent.com/chrisnott-unicon/bestphotos/main"

BLOCKS = ("STATS", "CLIENTS", "FLAGSHIP", "INSIGHTS")


def e(s) -> str:
    return html.escape(str(s), quote=True)


def img(path: str, w: int) -> str:
    return f"https://wsrv.nl/?url={PHOTOS}/{urllib.parse.quote(path)}&w={w}&output=webp&q=80"


def marker(name: str) -> tuple[str, str]:
    return (f"<!-- HOME:{name}:START - generated by tools/homepage.py, do not edit by hand -->",
            f"<!-- HOME:{name}:END -->")


# ----------------------------------------------------------------- sections

def render_stats(d: dict) -> str:
    t = d["totals"]
    cells = [
        (str(t["projects"]), "Projects Delivered"),
        (str(t["years_active"]), "Years Executing"),
        (t["delivered_value"], "Delivered Value"),
        (f"CIDB {t['cidb'].split(' /')[0]}", "National Grading"),
    ]
    tiles = "".join(f"""
                <div class="bg-white p-6 md:p-8 text-center sm:text-left">
                    <p class="text-3xl md:text-4xl font-black tracking-tighter text-unicon-black">{e(v)}</p>
                    <p class="mt-2 text-[9px] md:text-[10px] font-bold uppercase tracking-widest text-gray-500">{e(k)}</p>
                </div>""" for v, k in cells)
    return f"""
    <section class="bg-unicon-border py-px" aria-label="Portfolio at a glance">
        <div class="max-w-[90rem] mx-auto px-6 sm:px-8 lg:px-12">
            <div class="grid grid-cols-2 sm:grid-cols-4 gap-px bg-unicon-border">{tiles}
            </div>
            <p class="py-4 text-center text-[10px] font-mono uppercase tracking-widest text-gray-500">
                Every project since {t['first_year']} is listed in our
                <a href="{BASE}/projects.html" target="_top" class="text-unicon-green hover:underline underline-offset-4">public project database</a>
            </p>
        </div>
    </section>"""


def render_clients(d: dict) -> str:
    names = "".join(f"""
                    <span class="px-4 py-2 border border-unicon-border bg-white text-[10px] md:text-xs font-bold uppercase tracking-widest text-unicon-black">{e(n)}</span>"""
                    for n in d["named_clients"])
    top = d["repeat_clients"][0]
    rows = "".join(f"""
                        <li class="flex items-baseline justify-between gap-4 border-b border-unicon-border py-3">
                            <span class="text-sm font-light text-gray-700">{e(c['name'])}</span>
                            <span class="shrink-0 text-sm font-bold text-unicon-black">{c['contracts']} contracts</span>
                        </li>""" for c in d["repeat_clients"][:6])
    return f"""
    <section class="py-20 md:py-24 bg-white border-b border-unicon-border" aria-labelledby="clients-heading">
        <div class="max-w-[90rem] mx-auto px-6 sm:px-8 lg:px-12">
            <div class="text-center mb-12">
                <p class="text-unicon-green font-bold uppercase tracking-widest text-[10px] md:text-xs mb-3">Who We Build For</p>
                <h2 id="clients-heading" class="text-3xl md:text-5xl font-extrabold tracking-tight uppercase">Trusted With <span class="text-unicon-green">Critical</span> Infrastructure.</h2>
            </div>
            <div class="flex flex-wrap justify-center gap-3 mb-16">{names}
            </div>
            <div class="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16 items-center">
                <div>
                    <p class="text-5xl md:text-6xl font-black tracking-tighter text-unicon-black">{top['contracts']}</p>
                    <p class="mt-3 text-lg md:text-xl font-light leading-relaxed text-gray-700">
                        separate contracts awarded to us by <strong class="font-bold text-unicon-black">{e(top['name'])}</strong> alone.
                    </p>
                    <p class="mt-5 text-sm font-light leading-relaxed text-gray-600">
                        Repeat appointments are the measure we pay most attention to. Clients who have seen how we
                        run a site come back — and in bulk water, where a leak is a failure, that is the reference
                        that matters.
                    </p>
                </div>
                <div>
                    <p class="mb-4 text-[10px] font-bold uppercase tracking-widest text-gray-500">Contracts awarded, by client</p>
                    <ul class="border-t border-unicon-border">{rows}
                    </ul>
                </div>
            </div>
        </div>
    </section>"""


def render_flagship(d: dict) -> str:
    cards = []
    for f in d["flagships"]:
        note = "" if f.get("verified") else "\n            <!-- photo: representative of the discipline, not a verified photograph of this project -->"
        cards.append(f"""
                <article class="group relative overflow-hidden border border-unicon-border bg-white shadow-sm transition-colors hover:border-unicon-green">{note}
                    <div class="relative aspect-[16/10] overflow-hidden">
                        <img src="{img(f['image'], 800)}" alt="{e(f['alt'])}" loading="lazy" decoding="async"
                             class="h-full w-full object-cover grayscale-[35%] transition duration-700 group-hover:scale-[1.04] group-hover:grayscale-0">
                        <span class="absolute left-4 top-4 bg-unicon-green px-3 py-1 text-[9px] font-bold uppercase tracking-widest text-white shadow-md">{e(f['sector'])}</span>
                    </div>
                    <div class="p-6 md:p-8">
                        <p class="text-[10px] font-mono uppercase tracking-widest text-gray-400">{f['year']} · {e(f['client'])}</p>
                        <h3 class="mt-2 text-xl font-bold uppercase tracking-tight text-unicon-black">{e(f['name'])}</h3>
                        <p class="mt-3 text-sm font-light leading-relaxed text-gray-600">{e(f['detail'])}</p>
                    </div>
                </article>""")
    return f"""
    <section class="py-20 md:py-28 bg-unicon-slate border-b border-unicon-border" aria-labelledby="flagship-heading">
        <div class="max-w-[90rem] mx-auto px-6 sm:px-8 lg:px-12">
            <div class="mb-12 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
                <div>
                    <p class="text-unicon-green font-bold uppercase tracking-widest text-[10px] md:text-xs mb-3">Signature Works</p>
                    <h2 id="flagship-heading" class="text-3xl md:text-5xl font-extrabold tracking-tight uppercase">Recent Flagships.</h2>
                </div>
                <a href="{BASE}/projects.html" target="_top" class="shrink-0 text-[10px] font-bold uppercase tracking-widest text-unicon-green hover:text-unicon-black transition-colors">
                    All {d['totals']['projects']} projects <i class="fa-solid fa-arrow-right ml-1"></i>
                </a>
            </div>
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8">{''.join(cards)}
            </div>
        </div>
    </section>"""


def latest_articles(n: int = 2) -> list[dict]:
    if not os.path.exists(FEED):
        return []
    raw = open(FEED, encoding="utf-8").read()
    out = []
    for block in re.findall(r"<item>(.*?)</item>", raw, re.S)[:n]:
        def g(tag):
            m = re.search(rf"<{tag}>(.*?)</{tag}>", block, re.S)
            return html.unescape(m.group(1).strip()) if m else ""
        out.append({"title": g("title"), "link": g("link"),
                    "desc": g("description"), "cat": g("category"),
                    "date": g("pubDate")})
    return out


def render_insights(d: dict) -> str:
    arts = latest_articles(2)
    if not arts:
        return "\n    <!-- no published articles yet -->"
    cards = []
    for a in arts:
        try:
            when = datetime.strptime(a["date"][:16].strip(), "%a, %d %b %Y").strftime("%d %B %Y")
        except ValueError:
            when = ""
        cards.append(f"""
                <a href="{e(a['link'])}" target="_top" class="group block border border-unicon-border bg-white p-8 transition-colors hover:border-unicon-green">
                    <p class="text-[10px] font-mono uppercase tracking-widest text-gray-400">{e(a['cat'])}{' · ' + e(when) if when else ''}</p>
                    <h3 class="mt-3 text-xl font-bold uppercase tracking-tight text-unicon-black group-hover:text-unicon-green transition-colors">{e(a['title'])}</h3>
                    <p class="mt-3 text-sm font-light leading-relaxed text-gray-600">{e(a['desc'][:180])}{'…' if len(a['desc']) > 180 else ''}</p>
                    <span class="mt-6 inline-block text-[10px] font-bold uppercase tracking-widest text-unicon-green">Read the report <i class="fa-solid fa-arrow-right ml-1"></i></span>
                </a>""")
    return f"""
    <section class="py-20 md:py-24 bg-white border-b border-unicon-border" aria-labelledby="insights-heading">
        <div class="max-w-[90rem] mx-auto px-6 sm:px-8 lg:px-12">
            <div class="mb-12 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
                <div>
                    <p class="text-unicon-green font-bold uppercase tracking-widest text-[10px] md:text-xs mb-3">From the Field</p>
                    <h2 id="insights-heading" class="text-3xl md:text-5xl font-extrabold tracking-tight uppercase">Engineering Insights.</h2>
                </div>
                <a href="{BASE}/communications/insights.html" target="_top" class="shrink-0 text-[10px] font-bold uppercase tracking-widest text-unicon-green hover:text-unicon-black transition-colors">
                    All insights <i class="fa-solid fa-arrow-right ml-1"></i>
                </a>
            </div>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6 md:gap-8">{''.join(cards)}
            </div>
        </div>
    </section>"""


# ----------------------------------------------------------------- driver

RENDERERS = {"STATS": render_stats, "CLIENTS": render_clients,
             "FLAGSHIP": render_flagship, "INSIGHTS": render_insights}


def build() -> None:
    d = json.load(open(DATA, encoding="utf-8"))
    src = open(INDEX, encoding="utf-8").read()
    original = src
    missing = []
    for name in BLOCKS:
        start, end = marker(name)
        if start not in src or end not in src:
            missing.append(name)
            continue
        body = RENDERERS[name](d)
        src = re.sub(re.escape(start) + r".*?" + re.escape(end),
                     lambda _m: start + body + "\n    " + end, src, flags=re.S)
    if missing:
        raise SystemExit(f"index.html is missing markers for: {', '.join(missing)}")
    if src != original:
        open(INDEX, "w", encoding="utf-8").write(src)
        print("index.html updated.")
    else:
        print("Already up to date.")


def check() -> None:
    d = json.load(open(DATA, encoding="utf-8"))
    src = open(INDEX, encoding="utf-8").read()
    ok = True
    for name in BLOCKS:
        start, end = marker(name)
        present = start in src and end in src
        ok &= present
        print(f"  [{'ok ' if present else 'MISSING'}] marker {name}")
    print(f"\n  {d['totals']['projects']} projects, {len(d['named_clients'])} named clients, "
          f"{len(d['flagships'])} flagships, {len(latest_articles(2))} article(s) available")
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("cmd", choices=["build", "check"])
    a = ap.parse_args()
    build() if a.cmd == "build" else check()
