#!/usr/bin/env python3
"""Insights publishing tool.

Each article under communications/insights/ carries its own metadata in a
JSON-LD <script type="application/ld+json"> block. That block is the single
source of truth — this tool reads it to regenerate the index and the RSS feed,
so adding an article never requires hand-editing insights.html.

Usage:
    python3 tools/insights.py check     validate every article's metadata
    python3 tools/insights.py build     regenerate the index cards and feed.xml
    python3 tools/insights.py new --slug <slug> --title "..." --category "..." \
                                  --summary "..." --image <url>
"""
from __future__ import annotations

import argparse
import glob
import html
import json
import os
import re
import sys
from datetime import datetime, timezone, timedelta

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ARTICLE_DIR = os.path.join(ROOT, "communications", "insights")
INDEX = os.path.join(ROOT, "communications", "insights.html")
FEED = os.path.join(ARTICLE_DIR, "feed.xml")
BASE = "https://www.uniconsa.co.za"
SAST = timezone(timedelta(hours=2))

CARDS_START = "<!-- INSIGHTS:CARDS:START - generated by tools/insights.py, do not edit by hand -->"
CARDS_END = "<!-- INSIGHTS:CARDS:END -->"

REQUIRED = ("headline", "description", "datePublished", "image", "articleSection")


# ----------------------------------------------------------------- read

def article_paths() -> list[str]:
    return sorted(p for p in glob.glob(os.path.join(ARTICLE_DIR, "*.html"))
                  if os.path.basename(p) != "index.html")


def read_meta(path: str) -> dict:
    """Pull the Article JSON-LD block out of an article file."""
    src = open(path, encoding="utf-8").read()
    for block in re.findall(
            r'<script type="application/ld\+json">\s*(\{.*?\})\s*</script>', src, re.S):
        try:
            data = json.loads(block)
        except json.JSONDecodeError as exc:
            raise ValueError(f"{os.path.basename(path)}: invalid JSON-LD ({exc})") from exc
        if data.get("@type") == "Article":
            data["_slug"] = os.path.splitext(os.path.basename(path))[0]
            data["_path"] = path
            data["_url"] = f"{BASE}/communications/insights/{os.path.basename(path)}"
            return data
    raise ValueError(f"{os.path.basename(path)}: no Article JSON-LD block found")


def load_all() -> list[dict]:
    items = [read_meta(p) for p in article_paths()]
    items.sort(key=lambda a: a["datePublished"], reverse=True)
    return items


def validate(items: list[dict]) -> list[str]:
    problems = []
    seen = {}
    for a in items:
        name = os.path.basename(a["_path"])
        for field in REQUIRED:
            if not a.get(field):
                problems.append(f"{name}: missing '{field}'")
        d = a.get("datePublished", "")
        if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", d or ""):
            problems.append(f"{name}: datePublished must be YYYY-MM-DD, got {d!r}")
        if len(a.get("headline", "")) > 110:
            problems.append(f"{name}: headline exceeds 110 chars ({len(a['headline'])})")
        if d in seen and d:
            pass  # same-day posts are fine
        seen[d] = name
    return problems


# ----------------------------------------------------------------- render

def fmt_date(iso: str) -> str:
    return datetime.strptime(iso, "%Y-%m-%d").strftime("%d %B %Y").lstrip("0")


def rfc822(iso: str) -> str:
    dt = datetime.strptime(iso, "%Y-%m-%d").replace(hour=9, tzinfo=SAST)
    return dt.strftime("%a, %d %b %Y %H:%M:%S %z")


def e(s: str) -> str:
    return html.escape(str(s), quote=True)


def card(a: dict) -> str:
    return f"""
                <article class="bg-white border border-unicon-border flex flex-col hover:border-unicon-green transition-colors shadow-sm group">
                    <div class="h-64 overflow-hidden relative">
                        <img src="{e(a['image'])}" loading="lazy" decoding="async" class="w-full h-full object-cover grayscale-[40%] group-hover:grayscale-0 group-hover:scale-105 transition-all duration-700" alt="{e(a.get('imageAlt') or a['headline'])}">
                        <div class="absolute top-4 left-4 bg-unicon-green text-white text-[9px] font-bold uppercase tracking-widest px-3 py-1 shadow-md">{e(a['articleSection'])}</div>
                    </div>
                    <div class="p-8 flex flex-col flex-grow">
                        <p class="text-[10px] text-gray-400 font-mono uppercase tracking-widest mb-3">
                            <time datetime="{e(a['datePublished'])}">{e(fmt_date(a['datePublished']))}</time>
                        </p>
                        <h3 class="text-2xl font-bold uppercase tracking-tight text-unicon-black mb-4 group-hover:text-unicon-green transition-colors">{e(a['headline'])}</h3>
                        <p class="text-gray-600 font-light text-sm leading-relaxed mb-8 flex-grow">{e(a['description'])}</p>
                        <div class="border-t border-unicon-border pt-4 flex justify-between items-center">
                            <a href="{e(a['_url'])}" target="_top" class="text-xs font-bold uppercase tracking-widest text-unicon-black hover:text-unicon-green transition-colors flex items-center gap-2">Read Full Report <i class="fa-solid fa-arrow-right"></i></a>
                        </div>
                    </div>
                </article>"""


def build_index(items: list[dict]) -> bool:
    src = open(INDEX, encoding="utf-8").read()
    if CARDS_START not in src or CARDS_END not in src:
        raise SystemExit(
            "insights.html is missing the generator markers.\n"
            f"Wrap the article card grid in:\n  {CARDS_START}\n  ...\n  {CARDS_END}")
    body = "".join(card(a) for a in items)
    new = re.sub(
        re.escape(CARDS_START) + r".*?" + re.escape(CARDS_END),
        CARDS_START + body + "\n                " + CARDS_END,
        src, flags=re.S)
    if new != src:
        open(INDEX, "w", encoding="utf-8").write(new)
        return True
    return False


def build_feed(items: list[dict]) -> bool:
    now = datetime.now(SAST).strftime("%a, %d %b %Y %H:%M:%S %z")
    entries = "".join(f"""
    <item>
      <title>{e(a['headline'])}</title>
      <link>{e(a['_url'])}</link>
      <guid isPermaLink="true">{e(a['_url'])}</guid>
      <pubDate>{rfc822(a['datePublished'])}</pubDate>
      <category>{e(a['articleSection'])}</category>
      <description>{e(a['description'])}</description>
    </item>""" for a in items)
    xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Unicon Construction — Insights</title>
    <link>{BASE}/communications/insights.html</link>
    <atom:link href="{BASE}/communications/insights/feed.xml" rel="self" type="application/rss+xml"/>
    <description>Field reports and engineering commentary from Unicon Construction — bulk water, heavy civils and turnkey infrastructure in Southern Africa.</description>
    <language>en-ZA</language>
    <copyright>Unicon Construction SA</copyright>
    <lastBuildDate>{now}</lastBuildDate>{entries}
  </channel>
</rss>
"""
    old = open(FEED, encoding="utf-8").read() if os.path.exists(FEED) else ""
    # ignore lastBuildDate when deciding whether anything really changed
    strip = lambda s: re.sub(r"<lastBuildDate>.*?</lastBuildDate>", "", s)
    if strip(old) != strip(xml):
        open(FEED, "w", encoding="utf-8").write(xml)
        return True
    return False


# ----------------------------------------------------------------- scaffold

TEMPLATE_SOURCE = os.path.join(ARTICLE_DIR, "40ml-reservoirs.html")


def scaffold(slug, title, category, summary, image):
    dest = os.path.join(ARTICLE_DIR, f"{slug}.html")
    if os.path.exists(dest):
        raise SystemExit(f"{dest} already exists")
    src = open(TEMPLATE_SOURCE, encoding="utf-8").read()
    today = datetime.now(SAST).strftime("%Y-%m-%d")
    old = read_meta(TEMPLATE_SOURCE)

    src = src.replace(old["image"], image)
    src = src.replace(old["headline"], title)
    src = src.replace(old["description"], summary)
    src = src.replace(f'"{old["articleSection"]}"', f'"{category}"')
    src = src.replace(f">{old['articleSection']}<", f">{category}<")
    src = src.replace(old["datePublished"], today)
    src = src.replace(fmt_date(old["datePublished"]), fmt_date(today))
    src = src.replace(f"insights/{old['_slug']}.html", f"insights/{slug}.html")

    body = re.search(r'(<div class="max-w-\[50rem\] mx-auto px-6 sm:px-8 article-body">)(.*?)(\n\s*</div>\s*</article>)', src, re.S)
    if body:
        src = src[:body.start(2)] + (
            "\n\n            <p>TODO: opening paragraph.</p>\n\n"
            "            <h2>TODO: section heading</h2>\n"
            "            <p>TODO: body.</p>\n"
        ) + src[body.end(2):]

    open(dest, "w", encoding="utf-8").write(src)
    print(f"created {os.path.relpath(dest, ROOT)} — edit the body, then run: python3 tools/insights.py build")


# ----------------------------------------------------------------- cli

def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("check")
    sub.add_parser("build")
    n = sub.add_parser("new")
    for f in ("slug", "title", "category", "summary", "image"):
        n.add_argument(f"--{f}", required=True)
    args = ap.parse_args()

    if args.cmd == "new":
        scaffold(args.slug, args.title, args.category, args.summary, args.image)
        return

    items = load_all()
    problems = validate(items)
    if problems:
        print("Metadata problems:", file=sys.stderr)
        for p in problems:
            print("  -", p, file=sys.stderr)
        sys.exit(1)

    if args.cmd == "check":
        print(f"{len(items)} article(s), all metadata valid:")
        for a in items:
            print(f"  {a['datePublished']}  {a['articleSection']:<20} {a['headline'][:60]}")
        return

    changed = [name for name, did in
               (("insights.html", build_index(items)), ("feed.xml", build_feed(items))) if did]
    print(f"{len(items)} article(s). " + (f"Updated: {', '.join(changed)}" if changed else "Already up to date."))


if __name__ == "__main__":
    main()
