#!/usr/bin/env python3
"""Own the structured data on every content page.

Thirty-two of forty content pages carried none, including all fourteen
capability pages and the contact page. Structured data is what makes a page
eligible for enhanced search results, and it is how AI assistants parse what a
firm does and where it works - which matters here, because GA4 shows a real
AI Assistant referral channel.

Everything is generated between markers, so it cannot drift from the site. The
breadcrumb trail is derived from tools/chrome.py's menu, so it always matches
the navigation. Capability pages get a Service block whose offer catalogue is
built from the scope groups in tools/build_pages.json - the same source as the
visible page - so the markup can never claim a capability the page does not.

Types already hand-authored on a page (the home page's GeneralContractor, the
project database's CollectionPage, the FAQ on the vendor page) are left alone
and never duplicated.

Run this after any generator that rewrites a whole page. tools/projects_page.py
regenerates projects.html from its template, so a block written before it runs
is discarded; the pipeline order is projects_page, homepage, careers, insights,
chrome, build_pages, schema, sitemap.

Usage:
    python3 tools/schema.py build     write the blocks
    python3 tools/schema.py check     fail if any page is out of date
"""
from __future__ import annotations

import glob
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import chrome

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = "https://www.uniconsa.co.za"
ORG_ID = f"{BASE}#organization"
LOGO = ("https://wsrv.nl/?url=raw.githubusercontent.com/chrisnott-unicon/"
        "UniconLogo/main/UniconBlk.png&w=400&output=webp")
MAP = "https://share.google/XC0JuqEbN4XYJeM5k"

START = "<!-- SCHEMA:START - generated by tools/schema.py, do not edit by hand -->"
END = "<!-- SCHEMA:END -->"

# Areas the project database actually shows work in.
AREA_SERVED = ["KwaZulu-Natal", "Eastern Cape", "South Africa"]

# Capability pages -> the service they describe.
SERVICES = {
    "build/water-engineering.html": ("Bulk Water and Wastewater Construction", "water-engineering"),
    "build/civil-engineering.html": ("Heavy Civil Engineering Construction", "civil-engineering"),
    "build/structural-engineering.html": ("Structural Concrete Construction", "structural-engineering"),
    "build/general-building.html": ("General Building Contracting", "general-building"),
    "build/industrial-logistics.html": ("Industrial and Logistics Construction", "industrial-logistics"),
    "build/agricultural-engineering.html": ("Agricultural Engineering and EPC", "agricultural-engineering"),
    "build/mining-infrastructure.html": ("Mining and Heavy Industry Infrastructure", "mining-infrastructure"),
    "build/renewable-energy.html": ("Renewable Energy Balance of Plant Civils", "renewable-energy"),
    "design/architecture.html": ("Architectural Design", None),
    "design/civil-engineering.html": ("Civil Engineering Design", None),
    "design/structural-engineering.html": ("Structural Engineering Design", None),
    "design/mechanical-electrical-engineering-mep.html": ("Mechanical and Electrical (MEP) Design", None),
    "design/constructability.html": ("BIM and Constructability Review", None),
    "manage/project-management.html": ("Construction Project Management", None),
    "manage/facility-management.html": ("Facility Management", None),
}
COLLECTIONS = {
    "projects/1990s-archive.html": "Projects delivered in the 1990s",
    "projects/2000s-archive.html": "Projects delivered in the 2000s",
    "projects/2010s-archive.html": "Projects delivered in the 2010s",
    "projects/2020s-&-active-projects.html": "Projects delivered since 2020 and currently active",
    "projects/photo-gallery.html": "Photographs from Unicon construction sites",
    "communications/insights.html": "Insights and industry commentary from Unicon Construction",
}
ABOUT = {
    "home/about.html", "home/history.html", "home/team.html", "home/ethos.html",
}


def url(p: str) -> str:
    return f"{BASE}/" + ("" if p == "index.html" else p)


def existing_types(s: str) -> set:
    """Types already present outside our generated block."""
    outside = re.sub(re.escape(START) + r".*?" + re.escape(END), "", s, flags=re.S)
    return set(re.findall(r'"@type"\s*:\s*"([^"]+)"', outside))


def breadcrumb(page: str):
    """Home > Section > Page, derived from the navigation menu."""
    items = [{"@type": "ListItem", "position": 1, "name": "Home", "item": url("index.html")}]
    title = None
    for label, hub, subs in chrome.MENU:
        names = {sp: sl for sl, sp in subs}
        if page == hub and page != "index.html":
            items.append({"@type": "ListItem", "position": 2, "name": label, "item": url(hub)})
            return items
        if page in names:
            if hub != page:
                items.append({"@type": "ListItem", "position": 2, "name": label, "item": url(hub)})
            items.append({"@type": "ListItem", "position": 3, "name": names[page], "item": url(page)})
            return items
    # not in the menu: fall back to the directory it lives in
    d = os.path.dirname(page)
    for label, hub, subs in chrome.MENU:
        if d and os.path.dirname(hub) == d:
            items.append({"@type": "ListItem", "position": 2, "name": label, "item": url(hub)})
            break
    if title:
        items.append(title)
    return items if len(items) > 1 else []


def offer_catalog(slug: str):
    """Build the offer catalogue from the page's own visible scope groups."""
    data = json.load(open(os.path.join(ROOT, "tools", "build_pages.json"), encoding="utf-8"))
    c = data.get(slug)
    if not c:
        return None
    return {
        "@type": "OfferCatalog",
        "name": "Scope of works",
        "itemListElement": [
            {"@type": "OfferCatalog", "name": g["title"],
             "itemListElement": [{"@type": "Offer",
                                  "itemOffered": {"@type": "Service", "name": i}}
                                 for i in g["items"]]}
            for g in c["scope"]
        ],
    }


def meta(s: str, name: str) -> str:
    m = re.search(rf'<meta name="{name}" content="(.*?)">', s, re.S)
    return m.group(1) if m else ""


def title_of(s: str) -> str:
    m = re.search(r"<title>(.*?)</title>", s, re.S)
    return m.group(1) if m else ""


def blocks_for(page: str, s: str) -> list:
    have = existing_types(s)
    out = []

    crumbs = breadcrumb(page)
    if crumbs and "BreadcrumbList" not in have:
        out.append({"@context": "https://schema.org", "@type": "BreadcrumbList",
                    "itemListElement": crumbs})

    if page in SERVICES and "Service" not in have:
        name, slug = SERVICES[page]
        d = {
            "@context": "https://schema.org",
            "@type": "Service",
            "name": name,
            "serviceType": name,
            "description": meta(s, "description"),
            "url": url(page),
            "provider": {"@id": ORG_ID},
            "areaServed": [{"@type": "AdministrativeArea", "name": a} for a in AREA_SERVED],
        }
        cat = offer_catalog(slug) if slug else None
        if cat:
            d["hasOfferCatalog"] = cat
        out.append(d)

    if page in COLLECTIONS and "CollectionPage" not in have:
        out.append({"@context": "https://schema.org", "@type": "CollectionPage",
                    "name": title_of(s), "description": COLLECTIONS[page], "url": url(page),
                    "isPartOf": {"@id": ORG_ID}})

    if page in ABOUT and "AboutPage" not in have:
        out.append({"@context": "https://schema.org", "@type": "AboutPage",
                    "name": title_of(s), "description": meta(s, "description"),
                    "url": url(page), "about": {"@id": ORG_ID}})

    if page == "contact.html" and "ContactPage" not in have:
        out.append({"@context": "https://schema.org", "@type": "ContactPage",
                    "name": title_of(s), "url": url(page),
                    "about": {
                        "@type": "GeneralContractor",
                        "@id": ORG_ID,
                        "name": "Unicon Construction (Pty) Ltd",
                        "url": f"{BASE}/",
                        "logo": LOGO,
                        "telephone": "+27664834709",
                        "email": "info@uniconsa.co.za",
                        "foundingDate": "1991",
                        "address": {"@type": "PostalAddress", "addressLocality": "Hilton",
                                    "addressRegion": "KwaZulu-Natal", "addressCountry": "ZA"},
                        "hasMap": MAP,
                        "areaServed": [{"@type": "AdministrativeArea", "name": a} for a in AREA_SERVED],
                        "sameAs": ["https://www.linkedin.com/company/unicon-construction",
                                   "https://www.facebook.com/uniconconstruction"],
                    }})
    return out


def render(blocks) -> str:
    return "\n".join('    <script type="application/ld+json">\n'
                     + json.dumps(b, indent=2, ensure_ascii=False) + "\n    </script>"
                     for b in blocks)


def pages():
    out = []
    for f in sorted(glob.glob(os.path.join(ROOT, "**", "*.html"), recursive=True)):
        rel = os.path.relpath(f, ROOT).replace(os.sep, "/")
        s = open(f, encoding="utf-8").read()
        if 'http-equiv="refresh"' in s or rel == "404.html":
            continue
        out.append(rel)
    return out


def main() -> None:
    cmd = sys.argv[1] if len(sys.argv) > 1 else "build"
    changed = []
    for page in pages():
        path = os.path.join(ROOT, page)
        s = old = open(path, encoding="utf-8").read()
        body = render(blocks_for(page, s))
        block = START + ("\n" + body if body else "") + "\n    " + END
        if START in s:
            s = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _m: block, s, flags=re.S)
        elif body:
            s = s.replace("</head>", "    " + block + "\n</head>", 1)
        if s != old:
            changed.append(page)
            if cmd != "check":
                open(path, "w", encoding="utf-8").write(s)

    if cmd == "check":
        if changed:
            print("Structured data is out of date. Run 'python3 tools/schema.py build':", file=sys.stderr)
            for p in changed:
                print("  -", p, file=sys.stderr)
            sys.exit(1)
        print(f"structured data is current on {len(pages())} pages.")
    else:
        print(f"{len(changed)} page(s) updated of {len(pages())}.")


if __name__ == "__main__":
    main()
