#!/usr/bin/env python3
"""Regenerate sitemap.xml from the pages actually on disk.

Written because the sitemap kept drifting: new pages were missed, dates went
stale, and a page that had been canonicalised away was still being advertised.
Generating it removes the class of problem rather than fixing one instance.

Rules:
  - every .html page is included, except 404.html
  - a page whose canonical points at a different URL is skipped, because
    advertising a URL you have canonicalised away sends a mixed signal
  - lastmod comes from the file's last commit date, so it reflects reality
  - the RSS feed is listed so crawlers can find it

Usage:
    python3 tools/sitemap.py build     rewrite sitemap.xml
    python3 tools/sitemap.py check     report drift without writing (exit 1 if any)
"""
from __future__ import annotations

import glob
import os
import re
import subprocess
import sys
from datetime import date

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = "https://www.uniconsa.co.za"
SITEMAP = os.path.join(ROOT, "sitemap.xml")
FEED = "communications/insights/feed.xml"
EXCLUDE = {"404.html"}

# section -> (priority, changefreq or None)
RULES = [
    (lambda p: p == "index.html",                       ("1.0", "weekly")),
    (lambda p: p == "projects.html",                    ("0.9", "weekly")),
    (lambda p: p == "communications/insights.html",     ("0.8", "weekly")),
    (lambda p: p in ("build.html", "design.html", "manage.html", "contact.html"), ("0.9", "monthly")),
    (lambda p: p.startswith("projects/"),               ("0.8", None)),
    (lambda p: p.startswith("communications/insights/"), ("0.7", None)),
    (lambda p: p.startswith(("build/", "design/", "manage/")), ("0.8", None)),
    (lambda p: p.startswith("home/"),                   ("0.7", None)),
    (lambda p: p.startswith("contact/"),                ("0.6", None)),
]


def rule_for(path: str) -> tuple[str, str | None]:
    for test, out in RULES:
        if test(path):
            return out
    return ("0.5", None)


def loc_for(path: str) -> str:
    return f"{BASE}/" if path == "index.html" else f"{BASE}/{path}"


def esc(u: str) -> str:
    return u.replace("&", "&amp;")


def last_modified(path: str) -> str:
    try:
        out = subprocess.run(
            ["git", "-C", ROOT, "log", "-1", "--format=%ad", "--date=short", "--", path],
            capture_output=True, text=True, timeout=20).stdout.strip()
        if re.fullmatch(r"\d{4}-\d{2}-\d{2}", out):
            return out
    except Exception:
        pass
    return date.today().isoformat()


def canonical_target(path: str) -> str | None:
    src = open(os.path.join(ROOT, path), encoding="utf-8").read()
    m = re.search(r'<link rel="canonical" href="([^"]+)"', src)
    if not m:
        return None
    return m.group(1).replace(BASE + "/", "").replace(BASE, "")


def pages() -> list[str]:
    found = []
    for f in glob.glob(os.path.join(ROOT, "**", "*.html"), recursive=True):
        rel = os.path.relpath(f, ROOT).replace(os.sep, "/")
        if rel in EXCLUDE:
            continue
        target = canonical_target(rel)
        # "" is the canonical form of index.html
        if target is not None and target not in ("", rel):
            continue
        if target == "" and rel != "index.html":
            continue
        found.append(rel)
    return sorted(found, key=lambda p: (p != "index.html", p))


def render() -> str:
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
           '',
           '  <!-- Generated by tools/sitemap.py - do not edit by hand -->']
    for p in pages():
        pri, freq = rule_for(p)
        out.append("  <url>")
        out.append(f"    <loc>{esc(loc_for(p))}</loc>")
        out.append(f"    <lastmod>{last_modified(p)}</lastmod>")
        if freq:
            out.append(f"    <changefreq>{freq}</changefreq>")
        out.append(f"    <priority>{pri}</priority>")
        out.append("  </url>")
    if os.path.exists(os.path.join(ROOT, FEED)):
        out.append("  <url>")
        out.append(f"    <loc>{BASE}/{FEED}</loc>")
        out.append(f"    <lastmod>{last_modified(FEED)}</lastmod>")
        out.append("    <changefreq>weekly</changefreq>")
        out.append("    <priority>0.5</priority>")
        out.append("  </url>")
    out.append("")
    out.append("</urlset>")
    return "\n".join(out) + "\n"


def main() -> None:
    cmd = sys.argv[1] if len(sys.argv) > 1 else "build"
    new = render()
    old = open(SITEMAP, encoding="utf-8").read() if os.path.exists(SITEMAP) else ""
    if cmd == "check":
        listed = set(re.findall(r"<loc>(.*?)</loc>", old))
        expected = set(re.findall(r"<loc>(.*?)</loc>", new))
        missing, extra = expected - listed, listed - expected
        for m in sorted(missing):
            print(f"  missing from sitemap: {m}")
        for x in sorted(extra):
            print(f"  should not be listed: {x}")
        print(f"{len(expected)} URLs expected, {len(missing)} missing, {len(extra)} stale")
        sys.exit(1 if (missing or extra) else 0)
    if new != old:
        open(SITEMAP, "w", encoding="utf-8").write(new)
        print(f"sitemap.xml regenerated: {len(re.findall(r'<url>', new))} URLs")
    else:
        print("sitemap.xml already up to date.")


if __name__ == "__main__":
    main()
